# 2025 Descriptive statistics

In [1]:
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
data = pd.read_csv("../data/sam3/cleaned_data_anon_teams.csv", low_memory=False)

In [3]:
# Limit to 2025 data
data = data[data['year'] == 2025]

# Add columns
# Add columns
data['nihss>10'] = (data['stroke_severity'] > 10).astype(int)
data['nihss>10_or_lvo'] = (
    (data['stroke_severity'] > 10) | (data['lvo'] == 1)
).astype(int)
data['discharge_mrs_0-1'] = (
    (data['discharge_disability'] >= 0) &
    (data['discharge_disability'] <= 1)
).astype(int)
data['discharge_mrs_0-2'] = (
    (data['discharge_disability'] >= 0) &
    (data['discharge_disability'] <= 2)
).astype(int)

In [5]:
descriptive_stats_all_2025 = data.describe().T
descriptive_stats_all_2025

,count,mean,std,min,25%,50%,75%,max
age,78399.0,74.025721,13.391993,37.5,67.5,77.5,82.5,92.5
male,78366.0,0.546997,0.497790,0.0,0.0,1.0,1.0,1.0
onset_to_arrival_time,59449.0,826.182022,2345.646311,1.0,114.0,253.0,776.0,129868.0
onset_known,78399.0,0.758288,0.428124,0.0,1.0,1.0,1.0,1.0
precise_onset_known,78399.0,0.356535,0.478979,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
thrombectomy_centre,78399.0,0.282427,0.450183,0.0,0.0,0.0,1.0,1.0
nihss>10,78399.0,0.220755,0.414759,0.0,0.0,0.0,0.0,1.0
nihss>10_or_lvo,78399.0,0.256292,0.436587,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-1,78399.0,0.255654,0.436231,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-2,78399.0,0.450937,0.497590,0.0,0.0,0.0,1.0,1.0

In [6]:
# Divide the data into two groups based on the 'thrombectomy_centre' column, and produce descriptive statistics for each group
thrombectomy_centre_data = data[data['thrombectomy_centre'] == 1]
non_thrombectomy_centre_data = data[data['thrombectomy_centre'] == 0]

descriptive_stats_thrombectomy_centre = thrombectomy_centre_data.describe().T
descriptive_stats_non_thrombectomy_centre = non_thrombectomy_centre_data.describe().T

In [7]:
descriptive_stats_thrombectomy_centre

,count,mean,std,min,25%,50%,75%,max
age,22142.0,72.917532,13.798499,37.5,62.5,77.5,82.5,92.5
male,22128.0,0.555179,0.496957,0.0,0.0,1.0,1.0,1.0
onset_to_arrival_time,17276.0,808.389731,2298.734199,1.0,112.0,254.0,779.0,90172.0
onset_known,22142.0,0.780237,0.414096,0.0,1.0,1.0,1.0,1.0
precise_onset_known,22142.0,0.395131,0.488890,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
thrombectomy_centre,22142.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
nihss>10,22142.0,0.243338,0.429107,0.0,0.0,0.0,0.0,1.0
nihss>10_or_lvo,22142.0,0.282043,0.450004,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-1,22142.0,0.240674,0.427502,0.0,0.0,0.0,0.0,1.0
discharge_mrs_0-2,22142.0,0.431443,0.495289,0.0,0.0,0.0,1.0,1.0

In [8]:
descriptive_stats_non_thrombectomy_centre

,count,mean,std,min,25%,50%,75%,max
age,56257.0,74.461889,13.203212,37.5,67.5,77.5,82.5,92.5
male,56238.0,0.543778,0.498084,0.0,0.0,1.0,1.0,1.0
onset_to_arrival_time,42173.0,833.470562,2364.583251,1.0,114.0,252.0,774.0,129868.0
onset_known,56257.0,0.749649,0.433219,0.0,0.0,1.0,1.0,1.0
precise_onset_known,56257.0,0.341344,0.474165,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
thrombectomy_centre,56257.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0
nihss>10,56257.0,0.211867,0.408635,0.0,0.0,0.0,0.0,1.0
nihss>10_or_lvo,56257.0,0.246156,0.430774,0.0,0.0,0.0,0.0,1.0
discharge_mrs_0-1,56257.0,0.261550,0.439483,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-2,56257.0,0.458610,0.498288,0.0,0.0,0.0,1.0,1.0

## Stats for ischaemic stroke

In [9]:
ischaemic_data = data[data['infarction'] == 1]
descriptive_stats_ischaemic_2025 = ischaemic_data.describe().T
descriptive_stats_ischaemic_2025.to_csv("./output/descriptive_stats_ischaemic_2025.csv", index=True)
descriptive_stats_ischaemic_2025

,count,mean,std,min,25%,50%,75%,max
age,67981.0,74.031457,13.337209,37.5,67.5,77.5,82.5,92.5
male,67952.0,0.549344,0.497563,0.0,0.0,1.0,1.0,1.0
onset_to_arrival_time,51508.0,859.222043,2432.355479,1.0,116.0,267.0,803.0,129868.0
onset_known,67981.0,0.757682,0.428489,0.0,1.0,1.0,1.0,1.0
precise_onset_known,67981.0,0.353922,0.478189,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
thrombectomy_centre,67981.0,0.278401,0.448215,0.0,0.0,0.0,1.0,1.0
nihss>10,67981.0,0.193333,0.394915,0.0,0.0,0.0,0.0,1.0
nihss>10_or_lvo,67981.0,0.234315,0.423573,0.0,0.0,0.0,0.0,1.0
discharge_mrs_0-1,67981.0,0.273047,0.445528,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-2,67981.0,0.478501,0.499541,0.0,0.0,0.0,1.0,1.0

In [10]:
# Divide the data into two groups based on the 'thrombectomy_centre' column, and produce descriptive statistics for each group
thrombectomy_centre_data = ischaemic_data[ischaemic_data['thrombectomy_centre'] == 1]
non_thrombectomy_centre_data = ischaemic_data[ischaemic_data['thrombectomy_centre'] == 0]
descriptive_stats_thrombectomy_centre_ischaemic_2025 = thrombectomy_centre_data.describe().T
descriptive_stats_non_thrombectomy_centre_ischaemic_2025 = non_thrombectomy_centre_data.describe().T

In [11]:
descriptive_stats_thrombectomy_centre_ischaemic_2025

,count,mean,std,min,25%,50%,75%,max
age,18926.0,72.964176,13.712653,37.5,62.5,77.5,82.5,92.5
male,18914.0,0.558369,0.496594,0.0,0.0,1.0,1.0,1.0
onset_to_arrival_time,14798.0,843.314434,2389.801263,1.0,116.0,269.0,808.0,90172.0
onset_known,18926.0,0.781887,0.412975,0.0,1.0,1.0,1.0,1.0
precise_onset_known,18926.0,0.392370,0.488291,0.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...
thrombectomy_centre,18926.0,1.000000,0.000000,1.0,1.0,1.0,1.0,1.0
nihss>10,18926.0,0.211032,0.408052,0.0,0.0,0.0,0.0,1.0
nihss>10_or_lvo,18926.0,0.256314,0.436609,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-1,18926.0,0.256948,0.436962,0.0,0.0,0.0,1.0,1.0
discharge_mrs_0-2,18926.0,0.459579,0.498377,0.0,0.0,0.0,1.0,1.0

In [12]:
descriptive_stats_non_thrombectomy_centre_ischaemic_2025

,count,mean,std,min,25%,50%,75%,max
age,49055.0,74.443227,13.166536,37.5,67.5,77.5,82.50,92.5
male,49038.0,0.545862,0.497897,0.0,0.0,1.0,1.00,1.0
onset_to_arrival_time,36710.0,865.634487,2449.303240,1.0,117.0,267.0,800.75,129868.0
onset_known,49055.0,0.748344,0.433969,0.0,0.0,1.0,1.00,1.0
precise_onset_known,49055.0,0.339089,0.473405,0.0,0.0,0.0,1.00,1.0
...,...,...,...,...,...,...,...,...
thrombectomy_centre,49055.0,0.000000,0.000000,0.0,0.0,0.0,0.00,0.0
nihss>10,49055.0,0.186505,0.389518,0.0,0.0,0.0,0.00,1.0
nihss>10_or_lvo,49055.0,0.225828,0.418131,0.0,0.0,0.0,0.00,1.0
discharge_mrs_0-1,49055.0,0.279258,0.448639,0.0,0.0,0.0,1.00,1.0
discharge_mrs_0-2,49055.0,0.485802,0.499803,0.0,0.0,0.0,1.00,1.0

In [13]:
### Save descriptive stats

In [14]:
descriptive_stats_all_2025.to_csv("./output/descriptive_stats_all_stroke_2025.csv", index=True)
descriptive_stats_thrombectomy_centre.to_csv("./output/descriptive_stats_all_stroke_thrombectomy_centre_2025.csv", index=True)
descriptive_stats_non_thrombectomy_centre.to_csv("./output/descriptive_stats_all_stroke_non_thrombectomy_centre_2025.csv", index=True)
descriptive_stats_thrombectomy_centre_ischaemic_2025.to_csv("./output/descriptive_stats_ischaemic_stroke_thrombectomy_centre_2025.csv", index=True)
descriptive_stats_non_thrombectomy_centre_ischaemic_2025.to_csv("./output/descriptive_stats_ischaemic_stroke_non_thrombectomy_centre_2025.csv", index=True)